### PR TITLE
Update to 1.0.0

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @rgommers!

I have #75 with more changes that will probably be needed. Feel free to close that one and port the changes here.

**Comment by rgommers** [comment]
Ah nice. Missed your PR, sorry. Looks like the ``pytest`` change is definitely needed, and the OpenBLAS version bump seems like a good idea too. Is the rest needed, or is that orthogonal?

**Comment by ocefpaf** [comment]
The rerendering can be done automatically with:

@conda-forge-admin, please rerender

Some of the tests will need the modifications because `.wasSuccessful()` and `scipy.linalg._calc_lwork` seems to be removed in `1.0.0`.

**Comment by rgommers** [comment]
Does it make more sense to close this one and merge gh-75?

**Comment by ocefpaf** [comment]
> Does it make more sense to close this one and merge gh-75?

Up to you I am OK either way :smile:

**Comment by rgommers** [comment]
Your PR was first and looks good, so let's go with that.

**Pull request closed without merging**
