### PR TITLE
Add thewchan to maintainers

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
Hey folks, another package need v1.5.4 as a dependency, wonder if I can be added to try to add that version to the repo

**Comment by rgommers** [comment]
HI @thewchan, why do you need to be added for that? Can't you just submit a PR that adds a 1.5.4 build?

Also, out of curiosity, what package is that?

**Comment by thewchan** [comment]
Oh if I don't need to be added to do that then that's fine, it's just I was under the impression I needed to be added. I can just submit a PR then. 

The package is this: https://github.com/shankarpandala/lazypredict

**Comment by rgommers** [comment]
> Oh if I don't need to be added to do that then that's fine, it's just I was under the impression I needed to be added.

You don't need to be, so I'll close this PR.

> The package is this: https://github.com/shankarpandala/lazypredict

thanks

**Comment by h-vetinari** [comment]
I created a branch [`v1.5`](https://github.com/conda-forge/scipy-feedstock/tree/v1.5) that you should `git checkout` and target your PR against (when opening it).

**Pull request closed without merging**
