### PR TITLE
Win meson clang

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Great job in getting to the fortran compilation! Now errors with
```
[133/1628] Compiling Fortran object scipy/special/libcdflib.a.p/cdflib_algdiv.f.obj
FAILED: scipy/special/libcdflib.a.p/cdflib_algdiv.f.obj 
"flang-new" "-Iscipy\special\libcdflib.a.p" "-Iscipy\special" "-I..\scipy\special" "-fcolor-diagnostics" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-Minform=inform" "-O3" "-module" "scipy\special\libcdflib.a.p" -MD -MQ scipy/special/libcdflib.a.p/cdflib_algdiv.f.obj -MF "scipy\special\libcdflib.a.p\cdflib_algdiv.f.obj.d" -o scipy/special/libcdflib.a.p/cdflib_algdiv.f.obj "-c" ../scipy/special/cdflib/algdiv.f
flang-new: error: unknown argument: '-Minform=inform'

flang-new: error: unknown argument: '-module'

flang-new: warning: scipy\special\libcdflib.a.p: 'linker' input unused

```

From a quick google search, `-Minform=inform` seems to be a PGI-ism (not even gfortran), and I cannot find where it would be added in scipy. Might be something meson is adding... CC @eli-schwartz

**Comment by rgommers** [comment]
> From a quick google search, `-Minform=inform` seems to be a PGI-ism (not even gfortran), and I cannot find where it would be added in scipy. Might be something meson is adding... CC @eli-schwartz

It's coming from the `FlangFortranCompiler` class in Meson: https://github.com/mesonbuild/meson/blob/74407670e1a4fb12605e17806b53c42b0559b343/mesonbuild/compilers/fortran.py#L462. I'm guessing that it may have worked in old-style Flang, otherwise that compiler support would be completely broken. However, I can't find it in the docs. @h-vetinari if you have an old-style Flang at hand, can you check?

**Comment by rgommers** [comment]
Oh, old-style Flang _was_ the PGI compiler pretty much, right? The returned link flags are `['-lflang', '-lpgmath']`. 

The `-module` error is similar, it's the default return value for Fortran compilers of `get_module_outdir_args` (same file I linked above). So I guess this is running into the limitations of pretending new-style and old-style Flang are the same.

**Comment by eli-schwartz** [comment]
I guess this is a compelling sign that supporting it for SciPy is going to need a pull request to meson to make it work.

If it was just the first error (-Minform) I'd suggest building with warning_level=0 to suppress meson adding any warning flags of its own (including that one).

**Comment by xhochy** [comment]
Given the problematic invocation below, what would be the correct one with new-style clang? I would then try to write a minimal translator so that we could move forward in the build at least by a bit.

```
"flang-new" "-Iscipy\special\libamos.a.p" "-Iscipy\special" "-I..\scipy\special" "-fcolor-diagnostics" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-Minform=inform" "-O3" "-module" "scipy\special\libamos.a.p" -MD -MQ scipy/special/libamos.a.p/amos_dgamln.f.obj -MF "scipy\special\libamos.a.p\amos_dgamln.f.obj.d" -o scipy/special/libamos.a.p/amos_dgamln.f.obj "-c" ../scipy/special/amos/dgamln.f
```

**Comment by xhochy** [comment]
Any ideas why `meson` / `flang-new` would behave differently when I add the wrapper script? It should be a pass-through.

**Comment by eli-schwartz** [comment]
I'm fine with either solution.

**Pull request closed without merging**
