### PR TITLE
Update to scipy 1.6.1 and fix osx-arm64 failure.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
This looks great, looking forward to the update!

**Comment by h-vetinari** [comment]
OP deserves a "Closes #159" 👍

**Comment by erykoff** [comment]
One of the drone builds seems to have timed out (unrelated, I expect), but otherwise this is ready @conda-forge/scipy

**Comment by jakirkham** [comment]
Yep restarted it 🙂

**Comment by erykoff** [comment]
Still broken and timing out. I don’t know anything about that build so I’m not sure what to do to help.

**Comment by erykoff** [comment]
With gfortran fixed the bot PR #159 took care of this.

**Pull request closed without merging**
