### PR TITLE
re-enable pythran on windows; test skip hyghiene

### PR DESCRIPTION
**Pull request by h-vetinari**
Had been disabled to unblock release of 1.8.0

Closes #196

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/pythran
SCIPY_USE_PYTHRAN was disabled on windows to unblock the release of 1.8.0. I'd like to re-enable it. Here's the current error (with linebreaks for readability)
```
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe
    /c /nologo /Ox /W3 /GL /DNDEBUG /MD
    -DENABLE_PYTHON_MODULE
    -D__PYTHRAN__=3
    -DPYTHRAN_BLAS_NONE
    -IC:/bld/scipy_1644121349820/_h_env/Library/include
    -IC:\bld\scipy_1644121349820\_h_env\lib\site-packages/pythran
    -IC:\bld\scipy_1644121349820\_h_env\lib\site-packages\numpy\core\include
    -IC:\bld\scipy_1644121349820\_h_env\lib\site-packages\numpy\core\include
    -IC:\bld\scipy_1644121349820\_h_env\include
    -IC:\bld\scipy_1644121349820\_h_env\include
    -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include
    -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include
    -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
    -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt
    -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared
    -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um
    -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt
    -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt
    -IC:\bld\scipy_1644121349820\_h_env\Library\include
    -IC:\bld\scipy_1644121349820\_h_env\Library\include
    /EHsc
    /Tpscipy/interpolate/_rbfinterp_pythran.cpp
    /Fobuild\temp.win-amd64-3.9\Release\scipy/interpolate/_rbfinterp_pythran.obj
    /std:c++14 /w /Zm1000" failed with exit status 2
  error: subprocess-exited-with-error
```

**Comment by h-vetinari** [comment]
OK, so it's not related to the old toolchain. Upon further inspection, the error is:
```
error C2559: 'std::enable_if<`anonymous-namespace'::pythonic::types::is_numexpr_arg<F>::value&&std::is_same<bool,F::dtype>::value&&F::value==&&!`anonymous-namespace'::pythonic::types::is_pod_array<F>::value,`anonymous-namespace'::pythonic::types::numpy_vexpr<`anonymous-namespace'::pythonic::types::ndarray<T,pS>,`anonymous-namespace'::pythonic::types::ndarray<long,`anonymous-namespace'::pythonic::types::pshape<long>>>>::type `anonymous-namespace'::pythonic::types::ndarray<T,pS>::operator [](const F &) const': cannot overload a member function without ref-qualifier with a member function with ref-qualifier
```
which I've tried to format below:
```
error C2559:
  'std::enable_if<
      `anonymous-namespace'::pythonic::types::is_numexpr_arg<F>::value
      &&std::is_same<bool,F::dtype>::value
      &&F::value==&&!`anonymous-namespace'::pythonic::types::is_pod_array<F>::value,
    `anonymous-namespace'::pythonic::types::numpy_vexpr<
      `anonymous-namespace'::pythonic::types::ndarray<T,pS>,
      `anonymous-namespace'::pythonic::types::ndarray<long,
        `anonymous-namespace'::pythonic::types::pshape<long>>
    >
  >::type
  `anonymous-namespace'::pythonic::types::ndarray<T,pS>::operator [](const F &) const':
cannot overload a member function without ref-qualifier with a member function with ref-qualifier
```

**Comment by isuruf** [comment]
See https://github.com/conda-forge/scipy-feedstock/pull/198#issuecomment-1024960790

**Comment by h-vetinari** [comment]
> See [#198 (comment)](https://github.com/conda-forge/scipy-feedstock/pull/198#issuecomment-1024960790)

Thanks. I saw that comment of course, but I'm unfortunately also in the camp of "[...] for a reason we can't figure out".

**Comment by isuruf** [comment]
Right. Then the above error messages you posted are not relevant. It's just that cl.exe is used instead of clang-cl.exe.

**Comment by h-vetinari** [comment]
@conda-forge/scipy @rgommers @tylerjereddy

This fixes windows+pythran (backporting https://github.com/scipy/scipy/pull/15531) and cleans up the test skips such that we should be able to expect green CI essentially all the time (enabling automerge & avoiding restarts). Backporting https://github.com/scipy/scipy/pull/15532 isn't strictly necessary, but I thought it more elegant than skipping `test_ldl_type_size_combinations`. Opinions welcome.

I'm happy to wait a bit longer so that the upstream PRs have time to receive some feedback, but IMO this would be good to go.

**Comment by serge-sans-paille** [comment]
thanks!

**Comment by h-vetinari** [comment]
> I'm not 100% sure if there's any conda-forge policy on not doing such a rebuild of `1.8.0`,

It just gets an incremented build number. :)

**Pull request merged**
