### PR TITLE
scipy 1.13.0

### PR DESCRIPTION
**Pull request by h-vetinari**
Cannot rebase #270 on the phone -> new PR

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by rgommers** [comment]
This looks reasonable, just a few minor test failures. This isn't building against numpy 2.0.0rc1 yet, I assume you want to leave that for a separate PR, which can rebuild 1.13.0 with a higher build number?

The macOS x86-64 PyPy build shows one failure:
```
[gw2] darwin -- Python 3.9.18 $PREFIX/bin/python
../_test_env_placehold/lib/pypy3.9/site-packages/scipy/sparse/tests/test_dok.py:163: in test_dunder_ror
    assert d.__ror__(d) == Asp.__ror__(d)
E   AttributeError: 'dict' object has no attribute '__ror__'. Did you mean: '__ior__'?
        Asp        = <3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Dictionary Of Keys format>
        d          = {(0, 1): 1, (0, 2): 2}

FAILED sparse/tests/test_dok.py::test_dunder_ror[dok_matrix] - AttributeError: 'dict' object has no attribute '__ror__'. Did you mean: '__ior__'?
```

```
_____________________ TestNNLS.test_nnls_inner_loop_case1 _____________________
[gw0] win32 -- Python 3.9.19 %PREFIX%\python.exe
..\_test_env\lib\site-packages\scipy\optimize\tests\test_nnls.py:101: in test_nnls_inner_loop_case1
    dact, _ = nnls(W @ A, W @ k)
        2.23606798,  2.23606798,  1.        ,  1.41421356,  1.73205081,
        1.        ,  1.41421356])
..\_test_env\lib\site-packages\scipy\optimize\_nnls.py:93: in nnls
    raise RuntimeError("Maximum number of iterations reached.")
E   RuntimeError: Maximum number of iterations reached.
        A          = array([[ 5.19615242,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 2.8284271...   , -1.        ],
       [ 2.82842712,  2.82842712,  2.82842712, ...,  2.82842712,
         2.82842712,  2.82842712]])
        atol       = None
        b          = array([   0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,...         11.27887984,    8.05634274,    0.        ,    4.07622283,
          0.        ,    0.        ,    0.        ])
        m          = 67
        maxiter    = None
        mode       = -1
        n          = 67
        rnorm      = 0.0
        x          = array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.      ...       , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

FAILED optimize/tests/test_nnls.py::TestNNLS::test_nnls_inner_loop_case1 - RuntimeError: Maximum number of iterations reached.
```

**Comment by h-vetinari** [comment]
Ignoring the fact that PyPy is not in a good state (crashing on windows, hanging on Linux, failing on osx), the only real issue at the moment is `TestNNLS.test_nnls_inner_loop_case1` failing on windows. We can skip it for now, but should raise an issue. 

> This isn't building against numpy 2.0.0rc1 yet, I assume you want to leave that for a separate PR, which can rebuild 1.13.0 with a higher build number?

Normally I'd want to test both variants in this PR, but zipping against numpy is a bit difficult because it's part of the `zip_keys` that contains `python` - this will be improved once we move that pin (through whatever mechanism) to `NPY_FEATURE_VERSION`. In any case the builds against numpy 2.0 can come later IMO.

**Comment by h-vetinari** [comment]
Another test failure on windows appeared post-merge, but only with 3.10:
```
=========================== short test summary info ===========================
FAILED linalg/tests/test_decomp.py::TestEig::test_falker - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-07
```
Already failed twice in the same way, restarting again...

**Pull request merged**
