### PR TITLE
Separate tests into their own package

### LINKED ISSUE #160: Separate tests into a `scipy-tests` package
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

The tests in the scipy package are quite large (11MiB on-disk size). Thus it would be nice if we could ship them in a separate conda package like we did for `pyarrow`: https://github.com/conda-forge/arrow-cpp-feedstock/blob/48de7951f41b685cd1112e2f85c7c016eac0f553/recipe/meta.yaml#L232 This would allow downstream consumers to still run the `scipy` tests in their environment but allow those that don't want to do this to not ship the tests at all.

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #160 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@xhochy, sorry, #169 caused conflicts (since this PR is indenting everything). Would you mind rebasing again? Otherwise I can take rebase & squash your commits.

I'd be in favour of getting this in soon

**Comment by h-vetinari** [comment]
Also, AFAICS, the useful-error-if-only-`scipy`-is-installed bit from #160 is still missing.

**Comment by xhochy** [comment]
Also the Windows build is failing. I will rebase and continue working on this. This is though a bit on the "hobby list" thus progress is quite slow here.

**Comment by mattip** [comment]
Replaced by #167, can be closed

**Pull request closed without merging**
