### PR TITLE
sane numpy matrix...

### PR DESCRIPTION
**Pull request by ocefpaf**
...and update `openblas` pinning.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Interesting failure with the latest `openblas` on `OS X`. I'll try pinning to the old one next:

```
..................................................................................................................................BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

/Users/travis/miniconda3/conda-bld/scipy_1501116734847/test_tmp/conda_test_runner.sh: line 2: 10908 Segmentation fault: 11  "/Users/travis/miniconda3/conda-bld/scipy_1501116734847/_t_env/bin/python" -s "/Users/travis/miniconda3/conda-bld/scipy_1501116734847/test_tmp/run_test.py"

TESTS FAILED: scipy-0.19.1-py27_blas_openblas_201.tar.bz2
```

**Comment by ocefpaf** [comment]
@isuruf do you have an idea why the latest `openblas` is failing? The old one seems fine :confused:

**Comment by isuruf** [comment]
@jakirkham might know more. Might be related to https://github.com/conda-forge/openblas-feedstock/issues/26

**Comment by ocefpaf** [comment]
>  Might be related to conda-forge/openblas-feedstock#26

Yep. I ended up in a thread with that same info. Anyways, I'll get this version on the channel and we can re-pin later to issue a new build with the latest `openblas`. (We can ditch all the `scipy` branches now! Everything we need builds in one go :tada:)

**Comment by isuruf** [comment]
It seems `0.2.20` was broken on non-glibc versions and there'll be a `0.2.21` build very soon

**Comment by isuruf** [comment]
https://github.com/xianyi/OpenBLAS/issues/1252

**Comment by ocefpaf** [comment]
Good to know. Thanks @isuruf!

**Pull request merged**
