### PR TITLE
Rebuild with unpatched & GA build-deps

### PR DESCRIPTION
**Pull request by h-vetinari**
We also don't need `llvm_rc` anymore! 🥳

### CODE REVIEW

**Comment by h-vetinari** [comment]
@eli-schwartz happy to report that (after the fixes we discussed) meson 1.6.0rc1 works for scipy in conda-forge! :)

**Comment by h-vetinari** [comment]
A year after #255, we're now able to build with "stock" packages. 🤩 

Things have come quite a way since then. :)

**Comment by eli-schwartz** [comment]
:tada:

**Comment by h-vetinari** [comment]
Yeah, flang is very noisy with unknown flags. In openblas I had to use `-w` to make it bearable. Hopefully this gets better over time.

**Pull request merged**
