### PR TITLE
Remove openblas hacks

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by rgommers** [comment]
@isuruf maybe add a description of why those workarounds are no longer needed?

**Comment by isuruf** [comment]
These are added here, https://github.com/conda-forge/openblas-feedstock/blob/master/recipe/build.sh#L43-L46

**Comment by rgommers** [comment]
TravisCI failure was ``The job exceeded the maximum time limit for jobs, and has been terminated.``

PR LGTM

**Comment by jakirkham** [comment]
Appears that it was just a random job that had that issue. Could have timed out as it was notably above the typical build time. Have restarted it.

**Comment by jakirkham** [comment]
Also LGTM.

**Comment by jakirkham** [comment]
Thanks @isuruf.

**Comment by jakirkham** [comment]
Backporting to the NumPy 1.11 branch in PR ( https://github.com/conda-forge/scipy-feedstock/pull/63 ).

**Pull request merged**
