### PR TITLE
DRAFT: enable pythran + pypy

### LINKED ISSUE #177: Enable pythran for pypy
Follow-up from #176

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #177

As of 07-2021, still a WIP since this is known to fail

### CODE REVIEW

**Comment by mattip** [comment]
Maybe serge-sans-paille/pythran#1817 (which is part of the recent 0.9.12 release) will help to debug this

**Comment by h-vetinari** [comment]
Thanks for opening this PR. Let's hope we can figure this out 🙃

**Comment by mattip** [comment]
It turns out PyPy only partially implements the compact unicode forms outlined in [the unicodeobject.h header file](https://foss.heptapod.net/pypy/pypy/-/blob/release-pypy3.7-v7.3.5/pypy/module/cpyext/parse/cpyext_unicodeobject.h#L84). There is a macro [`_PyUnicode_COMPACT_DATA`](https://foss.heptapod.net/pypy/pypy/-/blob/release-pypy3.7-v7.3.5/pypy/module/cpyext/include/unicodeobject.h#L135) used by pythran for performance reasons that does not currently work on PyPy. I opened [an issue](https://foss.heptapod.net/pypy/pypy/-/issues/3518).

**Comment by h-vetinari** [comment]
@mattip, do you think it's worth to rebuild pypy with the patch for https://foss.heptapod.net/pypy/pypy/-/issues/3518 to unblock this?

**Comment by mattip** [comment]
Maybe? I don't want to burden the conda-forge CI infrastructure more than necessary. It should be simple to test pythran on PyPy HEAD. I did try to set up some package testing at https://github.com/pypy/binary-testing, maybe we should add a pythran workflow there.

**Comment by h-vetinari** [comment]
> 
> 
> Maybe? I don't want to burden the conda-forge CI infrastructure more than necessary.

The pypy packages don't generate much traffic yet (see [here](https://anaconda.org/conda-forge/pypy3.7/files)), and runs in the azure CI can reasonably be considered to have no real cost (to CF). I think it would be worth it to close this gap. Would you mind opening a PR? - you'd probably be much faster, since I don't have a hg setup ready.

**Comment by mattip** [comment]
I started a [CI job](https://github.com/pypy/binary-testing/pull/2) to see how pythran does, let's see how that goes.

**Comment by h-vetinari** [comment]
I think it's great to add a pythran workflow, but I'm wondering if this would even catch the issue? Pythran was built just fine for pypy on its feedstock, for example. Testing the (absence of the) segfault in particular would need `_PyUnicode_COMPACT_DATA` to be exercised, right?

**Comment by mattip** [comment]
The [pythran-feedstock tests](https://github.com/conda-forge/pythran-feedstock/blob/master/recipe/meta.yaml#L50) are very minimal.

**Comment by mattip** [comment]
I am a bit scared of the patch because it was not trivial to get it right, and it is not very small.

**Comment by h-vetinari** [comment]
> 
> 
> I am a bit scared of the patch because it was not trivial to get it right, and it is not very small.

Fair enough... then I guess we wait until the next release (any idea when 7.3.6 might arrive?)

**Comment by mattip** [comment]
Around October

**Comment by h-vetinari** [comment]
@mattip
This now compiles on all platforms - congratulations! 🥳
I think we should fold this into #195 - thoughts?

**Comment by mattip** [comment]
Makes sense to follow upstream where possible.

**Comment by h-vetinari** [comment]
> 
> 
> Makes sense to follow upstream where possible.

I interpret this as: we should be building with pythran support also on pypy? I pushed the commit into #195, it works fine. I believe this PR can therefore be closed...

**Comment by mattip** [comment]
You understood me correctly. Thanks for churning away at this. Closing.

**Pull request closed without merging**
