### PR TITLE
Aarch migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
I need permissions

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@mariusvniekerk i skipped all the problematic tests. Hard to test aarch64 without the real device.

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
@mariusvniekerk I think this one is ready to go.

@conda-forge/scipy I mostly skipped "ultra high" precision tests that seem to depend on blas. This should take 5.5 hours to compile on aarch64, but I expect it to pass.

**Comment by mariusvniekerk** [comment]
and it DID compile, only 350 minutes!

**Comment by mariusvniekerk** [comment]
@hmaarrfk is this safe to merge?

**Comment by hmaarrfk** [comment]
I think so. Skips are high precision failures. It might fail due to some recent changes in openblas. Maybe retrigger? And wait 6 hours

**Pull request merged**
