### PR TITLE
Remove openblas hacks (NumPy 1.11)

### PR DESCRIPTION
**Pull request by jakirkham**
Backported from PR ( https://github.com/conda-forge/scipy-feedstock/pull/62 ) for the NumPy 1.11 branch.

cc @isuruf

### CODE REVIEW

**Comment by isuruf** [comment]
I have a question. Why is this branch building for osx? It's handled in master right?

**Comment by jakirkham** [comment]
Sorry I don't follow. Do you mean why are we running CIs on the PR?

**Comment by isuruf** [comment]
I mean in master, it builds linux np=1.11, osx np=1.11, osx np=1.12
In this branch, it builds linux np=1.12, osx np=1.11, osx np=1.12

**Comment by jakirkham** [comment]
Yeah, that's an error. We use to have it setup so that we had the `np` with a `linux` selector attached, but I think things got changed when we upgraded `scipy` and switched to `numpy` 1.12.

We could do PRs to fix that. Might be worth adding `[ci skip]` to cutdown on build time as these don't really change the builds themselves. Only restructures where they occur.

**Comment by jakirkham** [comment]
Have fixed the NumPy selection issue in PRs ( https://github.com/conda-forge/scipy-feedstock/pull/64 ), ( https://github.com/conda-forge/scipy-feedstock/pull/65 ), and ( https://github.com/conda-forge/scipy-feedstock/pull/66 ).

**Pull request merged**
