### PR TITLE
fix conditional for windows

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

~Work around problems with #180. So far just rerender before adding debug info~ Fix the conditional to avoid pythran on PyPy

### CODE REVIEW

**Comment by mattip** [comment]
@h-vetinari I am using a local run_conda_forge_build_setup_win.bat here without setting the pagefile.
I needed to
- copy the upstream file into `recipe/run_conda_forge_build_setup_win.bat` and remove the lines dealing with pagefile
- rerender

When I did that this feedstock got past the ci setup stage. One of the builds failed due to an intermittent internet failure. Perhaps we can merge this, restart the migration PR #180, merge it, finish PR #182 (release 1.7.1), and then go back to debugging the pagefile script?

**Comment by isuruf** [comment]
Let's remove the pagefile script in `conda-forge-ci-setup-feedstock` and restart here.

**Comment by mattip** [comment]
Pivoting this PR to a new problem: the [condition to deactivate pythran](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=360060&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea&l=648) was missing double-quotes

**Comment by h-vetinari** [comment]
Do you mind if I cherry-pick your commit to #180?

**Comment by mattip** [comment]
@h-vetinari yes of course. The change here is pointless, it does not run the windows/pypy CI anyway.

**Pull request closed without merging**
