### PR TITLE
Try cross compiling

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Looks like cross-compiling for the same OS and different architecture works. If `sys.platform` calls are replaced with `sysconfig.get_platform()` in numpy, we'll be able to cross compile for different OSes too.

**Comment by beckermr** [comment]
cc @erykoff

**Comment by rgommers** [comment]
@isuruf yes, happy to review/accept that. There's regular questions about cross-compiling. Distutils isn't really built for that and NumPy devs don't really have a need, so no one has spent a lot of effort on it. But if there's something like this we can do to make your life easier, then that sounds like a good idea.

**Comment by h-vetinari** [comment]
This has now landed in #193

**Pull request closed without merging**
