### PR TITLE
V1.5.4

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Passing on py36 and failing elsewhere sounds like an incompatibility with newer numpy's (even though that shouldn't happen).

I'm not sure how much effort this is worth. It's possible to skip the tests, although cleaner would be to restrict the numpy version (not sure if `numpy <1.21` is sufficient, py36 is stuck on 1.19) - @thewchan, can your usecase handle a restriction to older numpy?

**Comment by thewchan** [comment]
@h-vetinari 
Hmmm, the package I am trying to get on conda-forge says this in its `requirement.txt`:

```
numpy==1.19.1
```

Here's the link: [](https://github.com/shankarpandala/lazypredict)

**Comment by h-vetinari** [comment]
@thewchan 
This requirements file is very likely over-specified (in fact, locked), particularly down to the patch version -- e.g. there's numpy 1.19.3, which is extremely likely to be compatible with 1.19.1 but probably has fewer bugs. I would start building the recipe without these explicit pins (down to the minor version if absolutely necessary) and see if the upstream test suite runs through.

conda recipes generally do not pin dependencies down that hard, because it becomes very hard to combine such packages with others in an environment. Lower and upper bounds make much more sense from the POV of the resolver and usage patterns.

Once you have a PR on staged-recipes, you can also ping (one of) the upstream maintainers if they want to collaborate - and whether they have opinions on the pinning.

**Comment by thewchan** [comment]
In the event that upstream isn't responsive, is it possible to patch the requirement with looser pins?

**Comment by dopplershift** [comment]
@thewchan No patching should be necessary, you're specifying the requirement in `meta.yaml` for that package.

**Comment by thewchan** [comment]
I do already have a PR on staging, that's how I found out that it needed that version of Scipy, I'll try to relax the requirements for Scipy on that recipe and see if it works

https://github.com/conda-forge/staged-recipes/pull/15950

**Comment by thewchan** [comment]
@dopplershift it seems that the 1.5.4 is hardcoded in the package

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=366025&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823

**Comment by dopplershift** [comment]
In that case I would just avoid running `pip check`.

**Comment by thewchan** [comment]
Got it, I'll try that @dopplershift

**Comment by thewchan** [comment]
Resolved adding the other package without needing scipy 1.5.4, closing this PR. Thanks for everyone's help!

**Pull request closed without merging**
