### PR TITLE
Meson on unix

### PR DESCRIPTION
**Pull request by h-vetinari**
Cleaned up version of #205

Windows will have to wait for a capable fortran compiler that's not gfortran (flang [hopefully](https://github.com/conda-forge/flang-feedstock/pull/27)...? LFortran? Ifort somehow in conda-forge?)

Closes #205

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
This LGTM, thanks @h-vetinari!

I went through one native and one cross build log in detail, and the expected options are used, not much seems off. These are the only warnings that stood out:

```
WARNING:conda_build.build:The install/build script(s) for scipy deleted the following files (from dependencies) from the prefix:
['aarch64-conda-linux-gnu/lib/libquadmath.so*', 'aarch64-conda-linux-gnu/lib/libstdc++.so.6.0.29']
This will cause the post-link checks to mis-report. Please try not to delete and files (DSOs in particular) from the prefix
```

```
Warning: rpath /home/conda/feedstock_root/build_artifacts/scipy_1681714748500/_build_env/lib is outside prefix /home/conda/feedstock_root/build_artifacts/scipy_1681714748500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place (removing it)
```

```
WARNING :: Failed to get_static_lib_exports(/home/conda/feedstock_root/build_artifacts/scipy_1681714748500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libtkstub8.6.a)
Unknown format
```

I think that's all harmless.

**Comment by h-vetinari** [comment]
Thanks for the review! Yes, those warnings are irrelevant. Also got Isuru's OK for the rebase of his changes, merging.

**Comment by moorepants** [comment]
Is there a reason the build number was not bumped in this PR?

**Comment by h-vetinari** [comment]
> Is there a reason the build number was not bumped in this PR?

It was an oversight, sorry about that.

**Pull request merged**
