### PR TITLE
SciPy 1.11.2

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #245

### CODE REVIEW

**Comment by h-vetinari** [comment]
Hm. Not sure what's happening here:
```
   Creating library build\temp.win-amd64-3.10\Release\scipy\special\_ufuncs_cxx.cp310-win_amd64.lib and object build\temp.win-amd64-3.10\Release\scipy\special\_ufuncs_cxx.cp310-win_amd64.exp
error: Command "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\\bld\\scipy-split_1692316041459\\_h_env\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:C:\bld\scipy-split_1692316041459\_build_env\Library\mingw-w64\lib\gcc\x86_64-w64-mingw32\5.3.0 /LIBPATH:C:\bld\scipy-split_1692316041459\_h_env\libs /LIBPATH:C:\bld\scipy-split_1692316041459\_h_env\PCbuild\amd64 /LIBPATH:build\temp.win-amd64-3.10 /LIBPATH:C:\bld\scipy-split_1692316041459\_h_env\libs /LIBPATH:C:\bld\scipy-split_1692316041459\_h_env\PCbuild\amd64 /LIBPATH:build\temp.win-amd64-3.10 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64 /LIBPATH:C:\bld\scipy-split_1692316041459\_h_env\Library\lib npymath.lib /EXPORT:PyInit__ufuncs_cxx build\temp.win-amd64-3.10\Release\scipy\special\_ufuncs_cxx.obj build\temp.win-amd64-3.10\Release\scipy\special\sf_error.obj build\temp.win-amd64-3.10\Release\scipy\special\ellint_carlson_wrap.obj build\temp.win-amd64-3.10\Release\scipy\special\_faddeeva.obj build\temp.win-amd64-3.10\Release\scipy\special\Faddeeva.obj build\temp.win-amd64-3.10\Release\scipy\special\_wright.obj build\temp.win-amd64-3.10\Release\scipy\special\wright.obj /OUT:build\lib.win-amd64-3.10\scipy\special\_ufuncs_cxx.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\scipy\special\_ufuncs_cxx.cp310-win_amd64.lib" failed with exit status 1120
sf_error.obj : error LNK2001: unresolved external symbol wrap_PyUFunc_getfperr
  Hint on symbols that are defined and could potentially match:
    "int __cdecl wrap_PyUFunc_getfperr(void)" (?wrap_PyUFunc_getfperr@@YAHXZ)
build\lib.win-amd64-3.10\scipy\special\_ufuncs_cxx.cp310-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
```
There _is_ a symbol by that exact name, but somehow the linker doesn't consider it...? 🤔

**Comment by rgommers** [comment]
The last build still seems to use Cython 3.0, despite the added constraint. I think that is the cause of the missing symbol.

**Comment by h-vetinari** [comment]
> The last build still seems to use Cython 3.0, despite the added constraint

I missed one place where it was needed. ;)

**Comment by h-vetinari** [comment]
OK, getting annoyed with fixing pypy here. In it goes.

**Pull request merged**
